---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvPrefix:
    Type: String
    Default: ""
  HostedZoneName:
    Type: String
  LambdaVersion:
    Type: String
  RootDiscordUserId:
    Type: String

Resources:
  AuthTokenPostLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${LambdaBucket}/apilambda_cft_${LambdaVersion}.yml"
        - LambdaBucket: !ImportValue
            'Fn::Sub': "tehBot-${EnvPrefix}LambdaBucket"
          LambdaVersion: !Ref LambdaVersion
      Parameters:
        EnvPrefix: !Ref EnvPrefix
        Version: !Ref LambdaVersion
        Name: auth_token_post
        RootDiscordUserId: !Ref RootDiscordUserId
        HostedZoneName: !Ref HostedZoneName
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  TokenAuthorizerLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${LambdaBucket}/apilambda_cft_${LambdaVersion}.yml"
        - LambdaBucket: !ImportValue
            'Fn::Sub': "tehBot-${EnvPrefix}LambdaBucket"
          LambdaVersion: !Ref LambdaVersion
      Parameters:
        EnvPrefix: !Ref EnvPrefix
        Version: !Ref LambdaVersion
        Name: token_authorizer
        RootDiscordUserId: !Ref RootDiscordUserId
        HostedZoneName: !Ref HostedZoneName
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  QuotesGetLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${LambdaBucket}/apilambda_cft_${LambdaVersion}.yml"
        - LambdaBucket: !ImportValue
            'Fn::Sub': "tehBot-${EnvPrefix}LambdaBucket"
          LambdaVersion: !Ref LambdaVersion
      Parameters:
        EnvPrefix: !Ref EnvPrefix
        Version: !Ref LambdaVersion
        Name: quotes_get
        RootDiscordUserId: !Ref RootDiscordUserId
        HostedZoneName: !Ref HostedZoneName
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  
  QuotesPostLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${LambdaBucket}/apilambda_cft_${LambdaVersion}.yml"
        - LambdaBucket: !ImportValue
            'Fn::Sub': "tehBot-${EnvPrefix}LambdaBucket"
          LambdaVersion: !Ref LambdaVersion
      Parameters:
        EnvPrefix: !Ref EnvPrefix
        Version: !Ref LambdaVersion
        Name: quotes_post
        RootDiscordUserId: !Ref RootDiscordUserId
        HostedZoneName: !Ref HostedZoneName
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  QuotesSearchPostLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${LambdaBucket}/apilambda_cft_${LambdaVersion}.yml"
        - LambdaBucket: !ImportValue
            'Fn::Sub': "tehBot-${EnvPrefix}LambdaBucket"
          LambdaVersion: !Ref LambdaVersion
      Parameters:
        EnvPrefix: !Ref EnvPrefix
        Version: !Ref LambdaVersion
        Name: quotes_search_post
        RootDiscordUserId: !Ref RootDiscordUserId
        HostedZoneName: !Ref HostedZoneName
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  QuoteNamePatchLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${LambdaBucket}/apilambda_cft_${LambdaVersion}.yml"
        - LambdaBucket: !ImportValue
            'Fn::Sub': "tehBot-${EnvPrefix}LambdaBucket"
          LambdaVersion: !Ref LambdaVersion
      Parameters:
        EnvPrefix: !Ref EnvPrefix
        Version: !Ref LambdaVersion
        Name: quote_name_patch
        RootDiscordUserId: !Ref RootDiscordUserId
        HostedZoneName: !Ref HostedZoneName
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  QuoteNameDeleteLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${LambdaBucket}/apilambda_cft_${LambdaVersion}.yml"
        - LambdaBucket: !ImportValue
            'Fn::Sub': "tehBot-${EnvPrefix}LambdaBucket"
          LambdaVersion: !Ref LambdaVersion
      Parameters:
        EnvPrefix: !Ref EnvPrefix
        Version: !Ref LambdaVersion
        Name: quote_name_delete
        RootDiscordUserId: !Ref RootDiscordUserId
        HostedZoneName: !Ref HostedZoneName
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  ReinvitePostLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${LambdaBucket}/apilambda_cft_${LambdaVersion}.yml"
        - LambdaBucket: !ImportValue
            'Fn::Sub': "tehBot-${EnvPrefix}LambdaBucket"
          LambdaVersion: !Ref LambdaVersion
      Parameters:
        EnvPrefix: !Ref EnvPrefix
        Version: !Ref LambdaVersion
        Name: reinvite_post
        RootDiscordUserId: !Ref RootDiscordUserId
        HostedZoneName: !Ref HostedZoneName
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete