---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvPrefix:
    Type: String
    Default: ""
Resources:
  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: DeleteRule
            Status: Enabled
            ExpirationInDays: 2
  CacheBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: DeleteRule
            Prefix: "triangles/"
            Status: Enabled
            ExpirationInDays: 180
      VersioningConfiguration:
        Status: Enabled
  WebBucket:
    Type: AWS::S3::Bucket
    # Properties:
    #   AccessControl: PublicRead
Outputs:
  LambdaBucket:
    Value: !Ref LambdaBucket
    Export:
      Name: !Sub "tehBot-${EnvPrefix}LambdaBucket"
  CacheBucket:
    Value: !Ref CacheBucket
    Export:
      Name: !Sub "tehBot-${EnvPrefix}CacheBucket"
  WebBucket:
    Value: !Ref WebBucket
    Export:
      Name: !Sub "tehBot-${EnvPrefix}WebBucket"
  WebBucketDomain:
    Value: !GetAtt WebBucket.DomainName
    Export:
      Name: !Sub "tehBot-${EnvPrefix}WebBucketDomainName"