---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvPrefix:
    Type: String
    Default: ""

Resources:
  LambdaSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "tehBot/${EnvPrefix}lambdas"
      SecretString: "{}"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

Outputs:
  LambdaSecretsArn:
    Value: !Ref LambdaSecrets
    Export:
      Name: !Sub "tehBot-${EnvPrefix}LambdaSecretsArn"